# Generated by Django 2.1.3 on 2018-11-28 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_auto_20181127_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(blank=True, max_length=100)),
                ('subhours1', models.FloatField(blank=True)),
                ('sub2', models.CharField(blank=True, max_length=100)),
                ('subhours2', models.FloatField(blank=True)),
                ('sub3', models.CharField(blank=True, max_length=100)),
                ('subhours3', models.FloatField(blank=True)),
                ('sub4', models.CharField(blank=True, max_length=100)),
                ('subhours4', models.FloatField(blank=True)),
                ('sub5', models.CharField(blank=True, max_length=100)),
                ('subhours5', models.FloatField(blank=True)),
                ('sub6', models.CharField(blank=True, max_length=100)),
                ('subhours6', models.FloatField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
