# Generated by Django 2.1.3 on 2018-11-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_planner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
