# Generated by Django 2.1.3 on 2018-11-28 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20181128_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='student',
        ),
    ]
