# Generated by Django 2.1.3 on 2018-11-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_planner_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planner',
        ),
    ]
